fun main(args: Array<String>) {
    first()
}

fun first(){
    try {
    
    }catch (e: Exception){
        println(e.message)
    }
}
